// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3tjDMPvvZMdTaCU5nqDJPxbPfZ0KRVc',
    appId: '1:648107784864:web:6143798a0f455f6af527c5',
    messagingSenderId: '648107784864',
    projectId: 'notes-ffb9f',
    authDomain: 'notes-ffb9f.firebaseapp.com',
    storageBucket: 'notes-ffb9f.appspot.com',
    measurementId: 'G-Y3YTPKZREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtZJMSUdDIAscGypqXZkCm4iN45xN1Q4',
    appId: '1:648107784864:android:7acb3d1eb973d801f527c5',
    messagingSenderId: '648107784864',
    projectId: 'notes-ffb9f',
    storageBucket: 'notes-ffb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWa4bvW3x1JoV9wZV_1dUvFqcXBnUFxA',
    appId: '1:648107784864:ios:ba62152a7968113ff527c5',
    messagingSenderId: '648107784864',
    projectId: 'notes-ffb9f',
    storageBucket: 'notes-ffb9f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWa4bvW3x1JoV9wZV_1dUvFqcXBnUFxA',
    appId: '1:648107784864:ios:d44f54e579559313f527c5',
    messagingSenderId: '648107784864',
    projectId: 'notes-ffb9f',
    storageBucket: 'notes-ffb9f.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
